version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_crypto
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto_pass
      POSTGRES_DB: cryptoGateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_crypto
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_crypto
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: crypto
      RABBITMQ_DEFAULT_PASS: crypto_pass

volumes:
  postgres_data:
